spring:
  mvc:
    static-path-pattern: /static/**
  resources:
    spring:
      resources:
        static:
          locations: classpath:/static/

          server:
            error:
              path: /error